[GPU] Fix compilation errors: 'level_zero/ze_api.h' file not found
In file included from /home/runner/_work/openvino/openvino/openvino/src/plugins/intel_gpu/thirdparty/onednn_gpu/third_party/ngen/ngen_sycl.hpp:22:
/home/runner/_work/openvino/openvino/openvino/src/plugins/intel_gpu/thirdparty/onednn_gpu/third_party/ngen/ngen_level_zero.hpp:26:10: fatal error: 'level_zero/ze_api.h' file not found
   26 | #include <level_zero/ze_api.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
1 error generated.

Because the include path to level_zero is missing in LIB_INCLUDE_DIRS.

Signed-off-by: KUWAMURA Shin'ya <kuwa@fujitsu.com>