let's try shell syntax for upload artifact action...
It most likely won't work but I see strange output in the logs:
Error: No files were found with the provided path: /__w/openvino/openvino/install/tests/TEST*.xml
/runner/_work/openvino/openvino/install/tests/logs/failed/*.log
/runner/_work/openvino/openvino/install/tests/logs/crashed/*.log
/runner/_work/openvino/openvino/install/tests/logs/hanged/*.log
/runner/_work/openvino/openvino/install/tests/logs/interapted/*.log
/runner/_work/openvino/openvino/install/tests/logs/disabled_tests.log. No
artifacts will be uploaded.

So the first path is translated to the path inside the container
correctly and the rest are not O_o