[ARM] Enable OpenMP on ARM platforms (#25329)
### Details:

Apple's `llvm` does not support `-fopenmp`. Brew's `llvm` avoids this
issue on OpenVINO build, however ACL build fails with the error `clang:
error: unsupported argument 'libomp' to option '-fopenmp='`. The
solution is to use `gcc` on Apple:
```
CXX=/opt/homebrew/Cellar/gcc/14.1.0_1/bin/g++-14 CC=/opt/homebrew/Cellar/gcc/14.1.0_1/bin/gcc-14 cmake -DTHREADING=OMP ..
```
On Linux compiler issues were not observed.

`ACLScheduler` uses only 1 thread if OpenMP is used because
`parallel_get_num_threads()` returns 1 in non-parallel section. The fix
is suggested in https://github.com/openvinotoolkit/openvino/pull/25335

### Tickets:
 - *ticket-id*