[CAPI]Unicode support (#12985)
* Unicode support

Change-Id: I6da095b0f0b86eb0fa9c44ddb41fa40f82fbded2

* Unicode support load compile model from file and add test cases

Change-Id: Ic66c2b9d5bc7da44db85772fc55abb9a699f4b7d

* Fix build error in Windows

Change-Id: I98c686f5bef17bef63ec6937035fac011224a790

* Fix compile error caused by rebase

Change-Id: I1457ba6bfd6743855bf55d77a2103a558548a8a0

* Fix refefinition issue in Windows

In windows it reports below error:
  include\10.0.18362.0\um\winnt.h(1131): error C2365: 'BOOLEAN': redefinition; previous definition was 'enumerator'
  openvino\src\bindings\c\include\openvino/c/ov_common.h(105): note: see declaration of 'BOOLEAN'

Change-Id: Ic84b7f0d6e3de5ba6c37af39533a3ca2f2d17ad8

* Link ov::util to call unicode code function

Change-Id: Ib324173524b8fe9b7f523fe6b838e155ffbe0842

* rename BL0 to be BOOLEAN

* Boolean should be 8bits data