[GPU] fix lstm sequential ocl (#34467)
### Details:
- without it gets error: implicit declaration of function
'OUTPUT1_GET_INDEX' is invalid in OpenCL
 - found when debugging lstm
 - visible when forcing lstm onednn to return false in validate

### AI Assistance:
 - *AI assistance used: no / yes*
- *If yes, summarize how AI was used and what human validation was
performed (build/tests/manual checks).*