[Protopipe] Fix const reference binding in config parser
This fixes the following compile error, introduced by commit
64a330242e291e372e37f4344316deb63f6474fe:

```
src/plugins/intel_npu/tools/protopipe/src/parser/config.cpp:148:9: error: cannot bind non-const lvalue reference of type ‘ConfigNode::KeyValueProxy&’ to an rvalue of type ‘ConfigNode::KeyValueProxy’
  148 |         for (auto& child : node) {
      |         ^~~
```

Signed-off-by: Daniel Bermond <dbermond@archlinux.org>