Revert "[Snippets] extract invariants pass" (#25181)
Reverts openvinotoolkit/openvino#24044

Reverted due to failure in TF FE layer tests:
RuntimeError: Exception from
openvino\openvino\src\inference\src\cpp\core.cpp:107:
Exception from openvino\openvino\src\inference\src\dev\plugin.cpp:53:
Exception from
openvino\openvino\src\common\snippets\src\lowered\pass\assign_registers.cpp:315:
can't allocate registers for a snippet