Build fix for Visual Studio 2022 v17.8.22 (#33560)
### Details:
- Avoids internal compiler error in Visual Studio 2022 version 17.8.22
(and probably other versions) by simplifying the use of macro
PRECISION_LIMITS_FOR to require fewer inferred conversions.

Compiler error (from original code):
```
1>------ Build started: Project: openvino_transformations_obj, Configuration: RelWithDebInfo x64 ------
1>convert_quantize_dequantize.cpp
1>C:\Users\elpalmer\IntelGit\openvino\src\common\transformations\src\transformations\common_optimizations\convert_quantize_dequantize.cpp(146,1): error C1001: Internal compiler error.
1>C:\Users\elpalmer\IntelGit\openvino\src\common\transformations\src\transformations\common_optimizations\convert_quantize_dequantize.cpp(146,1): error C1001: (compiler file 'D:\a\_work\1\s\src\vctools\Compiler\CxxFE\sl\p1\c\convert.cpp', line 11356)
1>C:\Users\elpalmer\IntelGit\openvino\src\common\transformations\src\transformations\common_optimizations\convert_quantize_dequantize.cpp(146,1): error C1001:  To work around this problem, try simplifying or changing the program near the locations listed above.
1>C:\Users\elpalmer\IntelGit\openvino\src\common\transformations\src\transformations\common_optimizations\convert_quantize_dequantize.cpp(146,1): error C1001: If possible please provide a repro here: https://developercommunity.visualstudio.com 
1>C:\Users\elpalmer\IntelGit\openvino\src\common\transformations\src\transformations\common_optimizations\convert_quantize_dequantize.cpp(146,1): error C1001: Please choose the Technical Support command on the Visual C++ 
1>C:\Users\elpalmer\IntelGit\openvino\src\common\transformations\src\transformations\common_optimizations\convert_quantize_dequantize.cpp(146,1): error C1001:  Help menu, or open the Technical Support help file for more information
1>Done building project "openvino_transformations_obj.vcxproj" -- FAILED.
```

---------

Co-authored-by: Eric Palmer <epalmer@adobe.com>
Co-authored-by: Pawel Raasz <pawel.raasz@intel.com>