[Py OV] Remove deprecated openvino.runtime part 2 (#33106)
### Details:
- `openvino.runtime.CompiledModel` cannot be removed because CI's check
[ie_tests_win_llm_accuracy_vs2022_release](https://openvino-ci.toolbox.iotg.sclab.intel.com/job/private-ci/job/ie/job/ie-tests-windows-llm_accuracy/16301/)
uses cached `optimum_intel-1.26.1` and fails.
 -  Log fragments: 
 >INFO: Collecting optimum-intel[nncf,tests]
INFO: Using cached optimum_intel-1.26.1-py3-none-any.whl.metadata (13
kB)

>INFO: def task(self) -> Dict[str, Union[openvino.Model,
openvino.runtime.CompiledModel]]:
 INFO: AttributeError: module 'openvino' has no attribute 'runtime'
 
- `openvino.runtime.CompiledModel` was already removed from
`optimum-intel` https://github.com/huggingface/optimum-intel/pull/1533

### Tickets:
 - [CVS-129460](https://jira.devtools.intel.com/browse/CVS-129460)