NPUW: Automatically align MAX_PROMPT_LENGTH to CHUNK_SIZE (#31687)
Chunking (#31294 ) introduced a new requirement that `MAX_PROMPT_LEN`
should be a multiple of the `CHUNK_SIZE`.

As there were cases where people passed various odd `MAX_PROMPT_LEN`'s,
e.g. in benchmarking, the default alignment by 64 couldn't pass this
limitation.

This PR aligns the `MAX_PROMPT_LEN` by the `CHUNK_SIZE` if the chunking
is enabled.

## Before

```
(env20250809) C:\dmitry\ov253-debug>type test.yml
MAX_PROMPT_LEN: 300

(env20250809) C:\dmitry\ov253-debug>python ..\chat.py -d NPU -m TinyLlama-1.1B-Chat-v1.0_int4_sym_group128_dyn_stateful -c test.yml
Traceback (most recent call last):
  File "C:\dmitry\chat.py", line 95, in <module>
    Chat(args).run()
    ^^^^^^^^^^
  File "C:\dmitry\chat.py", line 40, in __init__
    self.pipeline = ov_genai.LLMPipeline(args.model_dir, args.device, **self.pipeline_config)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Exception from src\inference\src\cpp\core.cpp:112:
Exception from src\inference\src\dev\plugin.cpp:53:
Exception from src\plugins\intel_npu\src\plugin\npuw\llm_compiled_model.cpp:1153:
Configuration Error: The maximum prompt length (320) is not a multiple of chunk size (256). Please adjust NPUW_LLM_MAX_PROMPT_LEN to be a multiple of NPUW_LLM_PREFILL_CHUNK_SIZE.
```

## After

```
(env20250809) C:\dmitry\ov253-debug>type test.yml
MAX_PROMPT_LEN: 300

(env20250809) C:\dmitry\ov253-debug>python ..\chat.py -d NPU -m TinyLlama-1.1B-Chat-v1.0_int4_sym_group128_dyn_stateful -c test.yml
> Who is Mark Twain?
Mark Twain was an American writer, humorist, and social critic who is best known for his satirical works, including "The Adventures of Huckleberry Finn" and "The Gilded Age." He was born Samuel Langhorne Clemens in 1835 in Florida, Missouri, and died in 1910 in St. Louis, Missouri. Twain was a lifelong friend of President Abraham Lincoln and was a member of the Republican Party. He was also a member of the American Anti-Slavery Society and the American Anti-Imperialist League
```

### Tickets:
 - *ticket-id*