Handle networking issues on retrieving test image for Model Hub tests (#31911)
### Details:

Without the changes in this PR on networking errors on test image
retrieval the exception looks like this:
```
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f14a394acf0>
```

This PR adds more clarity to the error message produced in that case.