[GHA] Fix for Android workflow failure (#38139)
### Details:
Currently there are multiple CI failures, including on master branch, in
Android workflow:
```
/opt/android-sdk/cmdline-tools/20.0/bin/sdkmanager tools
Loading package information...                                                  
Loading local repository...                                                     
[                                       ] 3% Loading local repository...        
[                                       ] 3% Fetch remote repository...         
[=                                      ] 3% Fetch remote repository...         
[=                                      ] 4% Fetch remote repository...         
[=                                      ] 5% Fetch remote repository...         
[==                                     ] 5% Fetch remote repository...         
[==                                     ] 6% Fetch remote repository...         
[==                                     ] 7% Fetch remote repository...         
[==                                     ] 7% Computing updates...               
[===                                    ] 8% Computing updates...               
[===                                    ] 10% Computing updates...              
                                                                                
Warning: Failed to find package 'tools'
/__w/_actions/android-actions/setup-android/40fd30fb8d7440372e1316f5d1809ec01dcd3699/dist/index.js:22290
        error2 = new Error(`The process '${this.toolPath}' failed with exit code ${this.processExitCode}`);
                 ^

Error: The process '/opt/android-sdk/cmdline-tools/20.0/bin/sdkmanager' failed with exit code 1
    at _ExecState._setResult (/__w/_actions/android-actions/setup-android/40fd30fb8d7440372e1316f5d1809ec01dcd3699/dist/index.js:22290:18)
    at _ExecState.CheckComplete (/__w/_actions/android-actions/setup-android/40fd30fb8d7440372e1316f5d1809ec01dcd3699/dist/index.js:22276:12)
    at ChildProcess.<anonymous> (/__w/_actions/android-actions/setup-android/40fd30fb8d7440372e1316f5d1809ec01dcd3699/dist/index.js:22181:17)
    at ChildProcess.emit (node:events:509:28)
    at maybeClose (node:internal/child_process:1141:16)
    at ChildProcess._handle.onexit (node:internal/child_process:306:5)
```

There are plenty of AI-generated PRs on github.com claiming "tools"
package was removed after a prolonged period of deprecation (this, for
example https://github.com/betaflight/betaflight-configurator/pull/5526
, and there are more links inside), but **there's no information about
it from any reliable source**. Still, let's try this before removing
Android from required checks