[`EISW-109425`] [`NPU plugin`] [`ov::execution_devices`] Fix bad execution devices value for NPU plugin (#24407)
### Details:
- Certain `execution devices` tests for `compiled_model` would fail
like:
 ```

src\tests\functional\plugin\shared\src\behavior\compiled_model\properties.cpp(329):
error: Expected equality of these values:
  expectedTargets
    Which is: { "NPU.XXXX" }
  exeTargets
    Which is: { "NPU.AUTO_DETECT" }
 ```
To overcome this problem, tests' `expectedTargets` were updated to `NPU`
only, but the value got from `ov::execution_devices` config had to be
updated to `NPU` as well.

- Other problem occurred for `NPU_TILES` config where prefixed values
for `NPU_PLATFORM` config e.g. `NPUXXXX` were not standardized to digits
only, causing `NPU_STEPPING` and `NPU_MAX_TILES` to be missing from
local config.

### Tickets:
- Instantiation of shared compiled model tests is being tracked in
*EISW-109425*