[GHA] Pin fastcore to fix SyntaxError on get_images_to_build.py (#33674)
```
/__w/openvino/openvino/.github/actions/handle_docker/get_images_to_build.py:9: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.util import strtobool
Traceback (most recent call last):
  File "/__w/openvino/openvino/.github/actions/handle_docker/get_images_to_build.py", line 10, in <module>
    from helpers import *
  File "/__w/openvino/openvino/.github/actions/handle_docker/helpers.py", line 7, in <module>
    from ghapi.all import GhApi
  File "/usr/local/lib/python3.10/dist-packages/ghapi/all.py", line 1, in <module>
    from .core import *
  File "/usr/local/lib/python3.10/dist-packages/ghapi/core.py", line 7, in <module>
    from fastcore.all import *
  File "/usr/local/lib/python3.10/dist-packages/fastcore/all.py", line 9, in <module>
    from .script import *
  File "/usr/local/lib/python3.10/dist-packages/fastcore/script.py", line 15, in <module>
    from .docments import docments
  File "/usr/local/lib/python3.10/dist-packages/fastcore/docments.py", line 359
    sig_str = f"def {get_name(self.obj)}(\n    {'\n    '.join(lines)}\n{self._ret_str}"
                                                                                       ^
SyntaxError: f-string expression part cannot include a backslash
```

Pinning fastcore to last working release. Alternative would be to move
this action to use python3.12.

https://github.com/AnswerDotAI/fastcore/issues/751
https://jira.devtools.intel.com/browse/CVS-179495