[OV JS] Support openvino-node types in TypeScript (#31200)
### Details:
- Fix for `error TS2339: Property 'CompiledModel' does not exist on type
'NodeAddon'.` and others
 - Enable the following scenario:
```ts
function create_request(model: typeof ov.CompiledModel) {
  const val = model instanceof ov.CompiledModel;
  const result = model.createInferRequest();
}
```
 - Disable "@typescript-eslint/no-misused-new"
The `NodeAddon` interface and others represent how the exported
functions from the native module should be used and provide proper type
safety for TypeScript users. The `new()` signatures in those interfaces
are not intended for class implementation. Instead, they describe
existing native functionality.
- Interfaces like `InputTensorInfo` and `PreProcessSteps` are types that
support the `preprocess` namespace functionality and are not meant to be
created or used independently. It may change in the future

### Tickets:
 - [CVS-168512](https://jira.devtools.intel.com/browse/CVS-168512)