NPUW: changed _mm_loadu_si64 avx instruction to _mm_loadl_epi64, to support gcc < 9.0 (#26190)
### Details:
- trying to compile npu plugin with gcc 8.5 or lower version resulted
into issues with unsupported intrinsics
 ``` c++
 <source>:6:17: error: '_mm_loadu_si64' was not declared in this scope
     __m128i a = _mm_loadu_si64((const __m128i *)(data));
                 ^~~~~~~~~~~~~~
<source>:6:17: note: suggested alternative: '_mm_loadl_epi64'
     __m128i a = _mm_loadu_si64((const __m128i *)(data));
```
 - technically they might be different since _mm_loadu_si64 specifically doesn't require data alignment while _mm_loadl_epi64 not specifying them
 - checked generated asm code(gcc 14.1) , well they are different, but tests with memory loading at 8 bits step showed no difference, so I assume both functions can work on unaligned arrays
![image](https://github.com/user-attachments/assets/c70ea4c2-2ab2-487d-b611-83ffe1a34ad3)

  - npuw unit test soon will be available in OV, with ongoing PR https://github.com/openvinotoolkit/openvino/pull/25780, while i've tested them locally with new intrinsics

### Tickets:
 - *ticket-id* - 136269

Co-authored-by: Dmitry Matveev <dmitry.matveev@intel.com>