Don't install networkx with version 2.8.1
With new networkx release (2.8.1) some of MO tests started to fail
with following error:
```
def __setstate__(self, state):
    self._graph = G = state["_graph"]
    self._adjdict = G._pred if hasattr(G, "pred") else G._adj
    AttributeError: 'Graph' object has no attribute '_adj'
```

Seems like regression that was introduced in
https://github.com/networkx/networkx/commit/f50fc70b8cb6b4f5217a6d5505ba0e2b82b4761b